---
title: "How Has The Number Of Shootings in Toronto Changed?"
subtitle: ""
author: 
  - Fatimah Yunusa

thanks: "Code and data are available at: https://github.com/fatimahsy/Shootings.git"
date: 23 January 2024
date-format: long
abstract: "Recently, Canada has been named the safest country in the world. A major component of Canada's safety comes from the safety of Toronto. Data detailing the number of shootings that have occured between the years of 2014 to 2019 have been obtained an will be thouroughly analysed within this paper through the use of various figures. Our findings show that in general, the number of shootings have increased in Toronto. From this paper, we learn that although Canada is considered a safer county overall, the number of shootings in Toronto have increased and we also learnt that datasets do have certain biases attached to them. "
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
library(knitr)
library(opendatatoronto)
```


# Introduction

Over the years, having having data that describes and shows explicitly the number of shootings that have occurred has proven to be extremely valuable. It it provides information about how well a community is doing, law enforcement efficiency and the general well being of the area. In terms of Toronto, information about shooting occurrences will help shape policy and inform law makers and community shareholders where to focus their attention on. This paper focuses on the shooting occurrences between 2014-2019 in Toronto and aims to analyse shooting occurrences and their geographical locations between this time period.

It is important to note that current literature on this issue does not go beyond the surface of the issue, but rather, it just focuses on the number and the general trend. This study aims to bridge the gap and provide a nuanced and detailed explanation as to why these trends occur. This paper is structured using the following headings:Data,Results, Discussion & Conclusion. The Data section focuses on providing a brief explanation of the data and how they were obtained from `opendatatoronto` [@citeOpenDataToronto] including a brief discussion of the data cleaning process.The results secton will focus on the trends found after performing statistical analysis. The discussion section will provide further insight and detail onto the results of the analysis shown in the results section. Lastly, the conclusion section will sum everything up and highlight the most important findings of this paper. 


# Data {#sec-data}

Throughout this paper, we use data that has been obtained from the city of Toronto's `opendatatoronto` [@citeOpenDataToronto]. Mainly, we used the `Police Annual Statistical Report - Shooting Occurrences, 2022` [@citeData]. To collect and analyse this data, we use the Statistical program `R` [@citeR] and additional packages such as: `tidyverse` [@citeTidyverse],`ggplot2` [@citeGGPlot2], `knitr` [@citeKnitR], `janitor` [@citeJanitor],`readr` [@citeReadR], `stringr` [@citeStringR], `here` [@citeHere], `kableExtra` [@citeKable],`lubridate` [@citeLubridate], `dplyr` [@citeDplyr], and finally `tibble` [@citeTibble]. 



# Results


# Discussion

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point

## Weaknesses and next steps

For this paper, the many weaknesses lie in the dataset it self 

\newpage




\appendix



# Appendix {-}




\newpage


# References


